// Code generated by goplus from decoder.gp. DO NOT EDIT.
//goplus:v v0.28.0

package yqlib

import (
	"io"
)

type Decoder interface {
	Init(reader io.Reader) error
	Decode() (*CandidateNode, error)
}
