// Code generated by goplus from operator_self.gp. DO NOT EDIT.
//goplus:v v0.28.0

package yqlib

func selfOperator(_ *dataTreeNavigator, context Context, _ *ExpressionNode) (Context, error) {
	return context, nil
}
