// Code generated by goplus from security_prefs.gp. DO NOT EDIT.
//goplus:v v0.28.0

package yqlib

type SecurityPreferences struct {
	DisableEnvOps   bool
	DisableFileOps  bool
	EnableSystemOps bool
}

var ConfiguredSecurityPreferences = SecurityPreferences{
	DisableEnvOps:   false,
	DisableFileOps:  false,
	EnableSystemOps: false,
}
