// Code generated by goplus from shellvariables.gp. DO NOT EDIT.
//goplus:v v0.28.0

package yqlib

type ShellVariablesPreferences struct {
	KeySeparator string
	UnwrapScalar bool
}

func NewDefaultShellVariablesPreferences() ShellVariablesPreferences {
	return ShellVariablesPreferences{
		KeySeparator: "_",
		UnwrapScalar: false,
	}
}

var ConfiguredShellVariablesPreferences = NewDefaultShellVariablesPreferences()
