// Code generated by goplus from toml.gp. DO NOT EDIT.
//goplus:v v0.28.0

package yqlib

type TomlPreferences struct {
	ColorsEnabled bool
}

func NewDefaultTomlPreferences() TomlPreferences {
	return TomlPreferences{ColorsEnabled: false}
}

func (p *TomlPreferences) Copy() TomlPreferences {
	return TomlPreferences{ColorsEnabled: p.ColorsEnabled}
}

var ConfiguredTomlPreferences = NewDefaultTomlPreferences()
